
import React, { useState } from 'react';
import { Narrative } from '../types';
import clsx from 'clsx';
import { InfoIcon } from './icons/GeneralIcons';

interface MultiLineChartProps {
    narratives: Narrative[];
}

// Accessible palette designed for data visualization against dark/light backgrounds
const COLORS = [
    '#3B82F6', // Blue
    '#EF4444', // Red
    '#10B981', // Emerald
    '#F59E0B', // Amber
    '#8B5CF6', // Violet
    '#EC4899', // Pink
    '#06B6D4', // Cyan
];

export const MultiLineChart: React.FC<MultiLineChartProps> = ({ narratives }) => {
    const [tooltip, setTooltip] = useState<{
        x: number;
        y: number;
        title: string;
        date: string;
        value: number;
        color: string;
    } | null>(null);

    // Filter narratives with trend data and take top 5 by riskScore
    // We prioritize showing the most critical narratives
    const activeNarratives = narratives
        .filter(n => n.trendData && n.trendData.length > 0)
        .sort((a, b) => (b.riskScore || 0) - (a.riskScore || 0))
        .slice(0, 5);

    if (activeNarratives.length === 0) return null;

    // Assume consistency in dates (generated by same analysis run)
    const dates = activeNarratives[0].trendData!.map(d => d.date);
    const labels = dates.map(dateStr => {
        const date = new Date(dateStr);
        return `${date.getMonth() + 1}/${date.getDate()}`;
    });

    // Flatten all values to find global max for scaling the Y-axis
    const allValues = activeNarratives.flatMap(n => n.trendData!.map(d => d.volume));
    const maxValue = Math.max(...allValues, 10); // Minimum max of 10 to avoid flat lines on 0 volume

    // Chart Dimensions
    const width = 800;
    const height = 350; // Increased height to accommodate X-axis label
    const padding = 60; // Increased padding to accommodate Y-axis label
    const chartWidth = width - padding * 2;
    const chartHeight = height - padding * 2;

    // Helper scales
    const getX = (index: number) => padding + (index / (Math.max(labels.length - 1, 1))) * chartWidth;
    const getY = (value: number) => height - padding - (value / maxValue) * chartHeight;

    return (
        <div className="w-full bg-background-card border border-border rounded-xl p-5 shadow-sm animate-fade-in-up mb-6 relative group/chart">
            <div className="flex justify-between items-center mb-4">
                <div className="flex items-center gap-2">
                    <h3 className="text-lg font-bold text-text-primary">Narrative Velocity Comparison</h3>
                    <div className="group relative">
                        <InfoIcon className="h-4 w-4 text-text-secondary cursor-help opacity-70 hover:opacity-100 transition-opacity" />
                        <div className="absolute left-full top-1/2 -translate-y-1/2 ml-2 w-64 p-3 bg-background-card border border-border rounded-md shadow-lg text-xs text-text-secondary opacity-0 group-hover:opacity-100 transition-opacity pointer-events-none z-20">
                            <p className="font-semibold text-text-primary mb-1">About this Graph</p>
                            Compare the spread velocity of top-risk narratives over the analyzed period. Spikes indicate viral moments or coordinated amplification events.
                        </div>
                    </div>
                </div>
                <span className="text-xs font-medium text-text-secondary bg-background-secondary px-2 py-1 rounded border border-border">Top 5 by Risk Score</span>
            </div>
            
            <div className="w-full overflow-x-auto custom-scrollbar relative">
                <div className="min-w-[600px] relative">
                     <svg 
                        viewBox={`0 0 ${width} ${height}`} 
                        className="w-full h-auto overflow-visible select-none"
                        onMouseLeave={() => setTooltip(null)}
                    >
                        {/* Grid Lines & Y-Axis Labels */}
                        {[0, 0.25, 0.5, 0.75, 1].map((tick) => {
                            const y = height - padding - tick * chartHeight;
                            const value = Math.round(tick * maxValue);
                            return (
                                <g key={tick}>
                                    <line
                                        x1={padding}
                                        y1={y}
                                        x2={width - padding}
                                        y2={y}
                                        stroke="currentColor"
                                        strokeOpacity="0.1"
                                        strokeDasharray="4 4"
                                    />
                                    <text
                                        x={padding - 10}
                                        y={y + 4}
                                        textAnchor="end"
                                        className="text-[10px] fill-text-secondary font-mono"
                                    >
                                        {value}
                                    </text>
                                </g>
                            );
                        })}

                        {/* Y-Axis Title */}
                        <text
                            x={20}
                            y={height / 2}
                            textAnchor="middle"
                            transform={`rotate(-90 20 ${height / 2})`}
                            className="text-[11px] fill-text-secondary font-bold uppercase tracking-wide cursor-help opacity-70 hover:opacity-100 hover:fill-primary transition-all"
                        >
                            Engagement Volume
                            <title>Estimated aggregate volume of posts, shares, and interactions detected.</title>
                        </text>

                        {/* X-Axis Labels */}
                        {labels.map((label, i) => {
                             // Show every label if few points, otherwise skip
                             if (labels.length > 10 && i % 2 !== 0 && i !== labels.length - 1) return null;
                             
                             const x = getX(i);
                             return (
                                 <text
                                    key={i}
                                    x={x}
                                    y={height - padding + 20}
                                    textAnchor="middle"
                                    className="text-[10px] fill-text-secondary font-mono"
                                 >
                                     {label}
                                 </text>
                             )
                        })}

                         {/* X-Axis Title */}
                         <text
                            x={width / 2}
                            y={height - 15}
                            textAnchor="middle"
                            className="text-[11px] fill-text-secondary font-bold uppercase tracking-wide cursor-help opacity-70 hover:opacity-100 hover:fill-primary transition-all"
                        >
                            Analysis Timeline
                            <title>Dates of data collection and analysis period.</title>
                        </text>

                        {/* Data Lines */}
                        {activeNarratives.map((narrative, index) => {
                            const points = narrative.trendData!.map((d, i) => `${getX(i)},${getY(d.volume)}`).join(' ');
                            const color = COLORS[index % COLORS.length];
                            
                            return (
                                <g key={narrative.id} className="group/line">
                                    {/* Invisible thick line for easier hovering */}
                                    <polyline
                                        fill="none"
                                        stroke="transparent"
                                        strokeWidth="20"
                                        points={points}
                                        className="cursor-pointer"
                                    />
                                    {/* Actual visible line */}
                                    <polyline
                                        fill="none"
                                        stroke={color}
                                        strokeWidth="3"
                                        points={points}
                                        strokeLinecap="round"
                                        strokeLinejoin="round"
                                        className="transition-all duration-300 group-hover/line:stroke-[4] group-hover/line:opacity-100 opacity-80"
                                        style={{ filter: `drop-shadow(0 0 2px ${color}40)` }}
                                    />
                                    {/* Dots at each point */}
                                    {narrative.trendData!.map((d, i) => (
                                        <circle 
                                            key={i}
                                            cx={getX(i)}
                                            cy={getY(d.volume)}
                                            r="4"
                                            fill={color}
                                            className="opacity-0 group-hover/line:opacity-100 transition-opacity duration-200 cursor-crosshair"
                                            onMouseEnter={() => setTooltip({
                                                x: getX(i),
                                                y: getY(d.volume),
                                                title: narrative.title,
                                                date: labels[i],
                                                value: d.volume,
                                                color
                                            })}
                                        />
                                    ))}
                                </g>
                            );
                        })}
                    </svg>

                    {/* Tooltip Overlay */}
                    {tooltip && (
                        <div 
                            className="absolute pointer-events-none bg-background-card border border-border shadow-xl rounded-lg p-2.5 z-10 animate-fade-in-up"
                            style={{ 
                                left: `${(tooltip.x / width) * 100}%`, 
                                top: `${(tooltip.y / height) * 100}%`,
                                transform: 'translate(-50%, -120%)',
                                minWidth: '150px'
                            }}
                        >
                            <div className="flex items-center gap-2 mb-1">
                                <span className="w-2 h-2 rounded-full" style={{ backgroundColor: tooltip.color }}></span>
                                <span className="text-xs font-bold text-text-primary line-clamp-2 leading-tight">{tooltip.title}</span>
                            </div>
                            <div className="flex justify-between items-center text-[10px] text-text-secondary">
                                <span>{tooltip.date}</span>
                                <span className="font-mono font-bold text-text-primary">Vol: {tooltip.value}</span>
                            </div>
                            <div className="absolute bottom-[-5px] left-1/2 -translate-x-1/2 w-2.5 h-2.5 bg-background-card border-r border-b border-border transform rotate-45"></div>
                        </div>
                    )}
                </div>
            </div>

            {/* Legend */}
            <div className="flex flex-wrap gap-x-6 gap-y-2 mt-4 justify-center px-4">
                {activeNarratives.map((n, i) => (
                    <div key={n.id} className="flex items-center gap-2 group cursor-default">
                        <span 
                            className="w-3 h-3 rounded-full shadow-sm ring-1 ring-white/10" 
                            style={{ backgroundColor: COLORS[i % COLORS.length] }}
                        ></span>
                        <span className="text-xs font-medium text-text-secondary group-hover:text-text-primary transition-colors truncate max-w-[200px]" title={n.title}>
                            {n.title}
                        </span>
                    </div>
                ))}
            </div>
        </div>
    );
};
